---
name: Metrics
on:
  push:
    branches:
      - main
  schedule:
    # Every day at 09:00 JST
    - cron: "0 0 * * *"
  workflow_dispatch: {}

jobs:
  collect-metrics:
    name: Collect metrics
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Build stats
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: fabasoad
          base: header, activity, community, repositories, metadata
          config_timezone: Japan
          template: classic
          # Leetcode
          plugin_leetcode: yes
          plugin_leetcode_user: fabasoad
          plugin_leetcode_sections: solved, skills, recent
          # Achievements
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          # Languages
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_sections: recently-used
          plugin_languages_details: percentage
          plugin_languages_recent_days: 365
