# Visit https://github.com/lowlighter/metrics#-documentation for full reference
---
name: Metrics
on:
  # Lines below let you run workflow manually and on each commit
  push:
    branches:
      - main
      - add/metrics
  schedule:
    # Every day at 09:00 JST
    - cron: "0 0 * * *"
  workflow_dispatch: {}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Leetcode Stats
        uses: lowlighter/metrics@latest
        with:
          token: ${{ github.token }}
          filename: metrics/metrics-plugin-leetcode.svg
          base: ""
          plugin_leetcode: yes
          plugin_leetcode_user: fabasoad
          plugin_leetcode_sections: solved, skills, recent
